//! CI tripwire: `docs/cli.md` must match the live clap surface. This mirrors the
//! contract drift test (`fmf-core`'s `drift.rs`) so a stale reference fails a
//! plain `cargo test` — not only the pre-push hook, which `git push --no-verify`
//! can skip. Regenerate with `just cli-gen`.
//!
//! The render here is intentionally identical to `examples/codegen.rs`
//! (`cli_reference`): same banner, same `clap_markdown` call on the single
//! command tree. A divergence between the two surfaces as a loud test failure.

/// The committed reference, pinned at compile time (path relative to this file:
/// tests → fmf-cli → crates → engine → repo root).
const COMMITTED: &str = include_str!("../../../../docs/cli.md");

/// Re-render the CLI reference exactly as `just cli-gen` writes it.
fn rendered() -> String {
    format!(
        "<!-- Generated by `just cli-gen`; do not edit by hand. -->\n\n{}",
        clap_markdown::help_markdown_command(&fmf_cli::command())
    )
}

/// Compare ignoring line-ending style, so a CRLF checkout never reads as drift.
fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n")
}

#[test]
fn cli_md_matches_the_clap_surface() {
    assert_eq!(
        normalize(COMMITTED),
        normalize(&rendered()),
        "docs/cli.md is out of date — run `just cli-gen`"
    );
}
