//! Code generator for the `fmf` CLI, run via `just cli-gen`
//! (`cargo run -p fmf-cli --example codegen`).
//!
//! It renders two artefacts from the single clap command tree
//! (`fmf_cli::command()`):
//!
//! * shell completions (PowerShell/bash/zsh/fish) into `build/completions/`, an
//!   ignored build output for local inspection (the release bundle generates its
//!   own under `completions/` via the shipped `fmf completions <shell>` — see
//!   xtask publish — so the bundled scripts always match the shipped binary);
//! * the Markdown CLI reference at `docs/cli.md`, a committed, generated file
//!   surfaced in the docs site.
//!
//! `--check` re-renders `docs/cli.md` in memory and fails if it drifts from the
//! committed copy, the same tripwire shape as the contract drift check.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use clap_complete::Shell;

/// The repo root: this crate sits at `<root>/engine/crates/fmf-cli`.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("fmf-cli is three directories below the repo root")
        .to_path_buf()
}

/// The generated CLI reference Markdown, with a do-not-edit banner.
fn cli_reference() -> String {
    format!(
        "<!-- Generated by `just cli-gen`; do not edit by hand. -->\n\n{}",
        clap_markdown::help_markdown_command(&fmf_cli::command())
    )
}

/// Compare ignoring line-ending style, so a CRLF checkout never reads as drift.
fn same_text(a: &str, b: &str) -> bool {
    a.replace("\r\n", "\n") == b.replace("\r\n", "\n")
}

fn main() -> ExitCode {
    let root = repo_root();
    let doc_path = root.join("docs").join("cli.md");
    let reference = cli_reference();

    if std::env::args().any(|a| a == "--check") {
        let current = std::fs::read_to_string(&doc_path).unwrap_or_default();
        if same_text(&current, &reference) {
            println!("docs/cli.md is up to date");
            return ExitCode::SUCCESS;
        }
        eprintln!("docs/cli.md is out of date — run `just cli-gen`");
        return ExitCode::FAILURE;
    }

    std::fs::write(&doc_path, &reference).expect("write docs/cli.md");
    println!("wrote {}", doc_path.display());

    let completions = root.join("build").join("completions");
    std::fs::create_dir_all(&completions).expect("create build/completions");
    let mut command = fmf_cli::command();
    for shell in [Shell::PowerShell, Shell::Bash, Shell::Zsh, Shell::Fish] {
        let path = clap_complete::generate_to(shell, &mut command, "fmf", &completions)
            .expect("write completion script");
        println!("wrote {}", path.display());
    }
    ExitCode::SUCCESS
}
